version: '3.9'
services:
  draft-nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - draft-backend
    networks:
      - draft-backend-network

  draft-backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      # TODO conditionをつける
      - draft-postgres
      - draft-redis
    networks:
      - draft-backend-network

  draft-postgres:
    restart: always
    image: postgres:latest
    environment:
    # if not POSTGRES_USER and POSTGRES_DB, it will be "postgres".
      POSTGRES_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - draft-postgres-db:/var/lib/postgresql/data
    networks:
      - draft-backend-network

  draft-redis:
    restart: always
    image: "redis:latest"
    ports:
      - 6379:6379
    volumes:
      - draft-cache-redis:/var/lib/redis/data
    networks:
      - draft-backend-network

# docker volume create --name=draft-postgres-db
# docker volume create --name=draft-cache-redis
volumes:
  draft-postgres-db:
    external: true
  draft-cache-redis:
    external: true

networks:
  draft-backend-network:
    driver: bridge
    external: true