apiVersion: v1
kind: Service
metadata:
  name: {{ include "tech-blog-backend.fullname" . }}-app
  labels:
    {{ include "tech-blog-backend.labels" . | nindent 4 }}
spec:
  selector:
    {{ include "tech-blog-backend.appSelectorLabels" . | nindent 4 }}
  ports:
  - name: api-v1
    port: 8000
    protocol: TCP
    targetPort: 8000
  type: ClusterIP