apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tech-blog-backend.fullname" . }}-gateway
  labels:
    {{ include "tech-blog-backend.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tech-blog-backend.fullname" . }}-gateway
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: PodResource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50