apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tech-blog-backend.fullname" . }}-gateway
  labels:
    {{ include "tech-blog-backend.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{ include "tech-blog-backend.gatewaySelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "tech-blog-backend.gatewaySelectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "tech-blog-backend.fullname" . }}-gateway
        image: nginx:1.26.0-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "32Mi"
            cpu: "100m"
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/default.conf
            name: nginx-conf
            readOnly: true
            subPath: default.conf
          - mountPath: /etc/nginx/conf.d/upstream.conf
            name: nginx-conf
            readOnly: true
            subPath: upstream.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: {{ include "tech-blog-backend.fullname" . }}-nginx-conf
