{{ if .Values.prometheus.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tech-blog-backend.fullname" . }}-service-monitor
  labels:
    release: prometheus
    {{- include "tech-blog-backend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tech-blog-backend
  namespaceSelector:
    matchNames:
    - tech-blog
  endpoints:
    - port: api-v1
      path: metrics
      interval: 30s
{{ end }}