user:
  host: "0.0.0.0"
  port: 8000

frontend:
  domain: http://draft-front.com:3000

relationalDB:
  master:
    driver: "postgres"
    # host: "127.0.0.1"
    host: "postgres"
    port: "5432"
    user: "postgres"
    name: "postgres"
    password: "password"
    sslMode: "disable"
  repricas:
    - driver: "postgres"
      # host: "reprica"
      host: "postgres"
      # port: "15432"
      port: "5432"
      user: "postgres"
      name: "postgres"
      password: "password"
      sslMode: "disable"
    - driver: "postgres"
      host: "postgres"
      port: "5432"
      user: "postgres"
      name: "postgres"
      password: "password"
      sslMode: "disable"
    - driver: "postgres"
      host: "postgres"
      port: "5432"
      user: "postgres"
      name: "postgres"
      password: "password"
      sslMode: "disable"

cacheRedis:
  host: "redis"
  port: "6379"
  password: ""
  dbNumber: 0
  expires: 24h

twitter:
  api_key: XXXXXXXXXX
  api_key_secret: XXXXXXXXXX
  bearer_token: XXXXXXXXXX
  user_id: XXXXXXXXXX

access_token:
  secret_key: SECRETKEY
  expires: 30m

refresh_token:
  secret_key: SECRETKEY
  expires: 720h

csrf_token:
  key: 32-byte-long-auth-key

github:
  personal_token: XXXXXXXX